PREFIX up: <http://purl.uniprot.org/core/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX faldo: <http://biohackathon.org/resource/faldo#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?protein ?atype_label ?description ?begin ?end
WHERE {
  VALUES ?annot_type { up:Transmembrane_Annotation up:Topological_Domain_Annotation }
  ?protein up:annotation [
      up:range ?range ;
      rdfs:comment ?description ;
      a ?annot_type ] .
  ?annot_type rdfs:label ?atype_label .
  ?range (faldo:begin / faldo:position) ?begin ;
         (faldo:end / faldo:position) ?end .
}
